# permissions for end users to edit ironforges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ironforge-editor-role
rules:
- apiGroups:
  - ironrain.io
  resources:
  - ironforges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ironrain.io
  resources:
  - ironforges/status
  verbs:
  - get
