# permissions for end users to view ironforges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ironforge-viewer-role
rules:
- apiGroups:
  - ironrain.io
  resources:
  - ironforges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ironrain.io
  resources:
  - ironforges/status
  verbs:
  - get
