apiVersion: v1
kind: Service
metadata:  
  labels:
    ironforge-ide-object: servce
  name: {{ regexSplit "@+" .Values.auth.email -1 | first }}-ironforge-{{ .Values.ide.language }}-svc
spec:
  ports:
  - name: tcp-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: tcp-4180
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    ironforge-ide: {{ regexSplit "@+" .Values.auth.email -1 | first }}-ironforge-{{ .Values.ide.language }}  
  type: ClusterIP
