apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: ironforge-manager
  name: ironforge-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironforge-manager
  namespace: system
  labels:
    control-plane: ironforge-manager
spec:
  selector:
    matchLabels:
      control-plane: ironforge-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: ironforge-manager
    spec:
      containers:
      - image: ironrainindustries/ironforge-operator:v0.1
        args:
        - "--enable-leader-election"
        - "--leader-election-id=build"
        env:
        - name: KEYCLOAK_URL
          value: https://keycloak.keycloak.192.168.0.179.xip.io/auth
        - name: KEYCLOAK_SCOPE
          value: openid email profile
        - name: KEYCLOAK_GROUP
          value: code-users
        - name: KEYCLOAK_CLIENT_ID
          value: oauth2
        - name: KEYCLOAK_CLIENT_SECRET
          value: ff0f6ddb-ce8a-4998-8113-9c13efa6b438
        - name: AUTH_IMAGE_REGISTRY
          value: quay.io
        - name: AUTH_IMAGE_REPOSITORY
          value: oauth2-proxy/oauth2-proxy
        - name: AUTH_IMAGE_TAG
          value: v6.1.1
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 90Mi
          requests:
            cpu: 100m
            memory: 60Mi
      terminationGracePeriodSeconds: 10
